<template>
  <main class="mainContent">
    <h1 class="text-3xl font-bold underline text-alert-120">This is an Home page</h1>
    <h1 class="text-3xl font-bold underline text-alert-120">標題</h1>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Neque ea, error provident vel minima officiis in aperiam necessitatibus nihil? Impedit natus esse animi eveniet ad eum quasi in quam qui quisquam quae adipisci, sed sequi neque temporibus eaque repudiandae tempora hic odit. Voluptates sed dolorem facere! Numquam totam eaque, sapiente, ex dolor blanditiis error soluta, aliquam natus deleniti impedit assumenda placeat eveniet! Eligendi, nulla, nobis incidunt earum adipisci pariatur eum et distinctio soluta fugiat, voluptates eius autem ad tenetur obcaecati a dolorem esse magni architecto est. Nobis maxime commodi ducimus ab cum. Eius reiciendis nobis totam non vel. Voluptates obcaecati sit, provident, aliquid dolores perferendis optio dolorum odit, ipsam modi possimus est a atque excepturi officia enim voluptatem aspernatur facere tempore nostrum laborum? Deserunt magni sit quo aliquam perspiciatis minus sunt maxime. Repudiandae recusandae culpa ducimus nihil voluptate cupiditate et similique molestiae quia earum? Rerum qui nisi et iusto adipisci reprehenderit maiores deserunt aliquid dolor debitis assumenda distinctio quibusdam saepe incidunt sequi molestias quidem quae molestiae, cum tenetur? Sint magnam qui deserunt modi nemo sapiente odit quo eligendi esse nihil, omnis consequuntur eaque veritatis cum possimus reiciendis cupiditate corrupti quis sit quos temporibus earum unde! Eum molestiae, sit necessitatibus dolorum quos officia optio inventore ad incidunt totam veniam repellendus molestias excepturi, autem quisquam, laboriosam tempore corporis! Aliquid ducimus modi, sunt eum quod magni similique recusandae doloribus inventore! Optio, voluptates eum vel molestiae quam pariatur temporibus quo nostrum recusandae ut praesentium vitae ipsum esse beatae, assumenda fuga iste placeat? Perferendis cumque odio deserunt repudiandae ullam dolore aut dolorum doloribus voluptate. Tempore sequi rem harum alias placeat sint, ullam ipsam quis doloribus, ut ducimus reprehenderit natus, quo ex quae deleniti dicta. Recusandae quisquam at ullam. Iusto nesciunt veniam sequi quas iure commodi, impedit adipisci reiciendis nihil soluta. Voluptate beatae accusamus explicabo nihil!</p>
    <img src="/src/assets/images/home/hero-img1.jpg" alt="">
  </main>
</template>

<style scoped>

</style>
